#!/bin/bash
sudo mkdir /publico/Departametos
sudo mkdir /publico/Departamentos/Prensa
sudo mkdir /publico/Departamentos/Administracion
sudo mkdir /publico/Departamentos/Informatica
sudo mkdir /publico/Departamentos/Rectorado
